config/routes.rb
Witchcraft::Application.routes.draw do
  resources :stitches

  resources :scrolls

  resources :scribblings

  resources :witches

end

app/models/stitch.rb
class Stitch < ActiveRecord::Base
  attr_accessible :scribbling_id, :scroll_id
  
  validates_presence_of :scribbling_id, :scroll_id
  
  belongs_to :scroll
  belongs_to :scribbling
end

app/controllers/stitches_controller.rb
class StitchesController < ApplicationController
  # GET /stitches
  # GET /stitches.json
  def index
    @stitches = Stitch.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stitches }
    end
  end

  # GET /stitches/1
  # GET /stitches/1.json
  def show
    @stitch = Stitch.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @stitch }
    end
  end

  # GET /stitches/new
  # GET /stitches/new.json
  def new
    @stitch = Stitch.new :scroll_id => params[:scroll_id]

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @stitch }
    end
  end

  # GET /stitches/1/edit
  def edit
    @stitch = Stitch.find(params[:id])
  end

  # POST /stitches
  # POST /stitches.json
  def create
    @stitch = Stitch.new(params[:stitch])

    respond_to do |format|
      if @stitch.save
        format.html { redirect_to @stitch, notice: 'Stitch was successfully created.' }
        format.json { render json: @stitch, status: :created, location: @stitch }
      else
        format.html { render action: "new" }
        format.json { render json: @stitch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stitches/1
  # PUT /stitches/1.json
  def update
    @stitch = Stitch.find(params[:id])

    respond_to do |format|
      if @stitch.update_attributes(params[:stitch])
        format.html { redirect_to @stitch, notice: 'Stitch was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @stitch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stitches/1
  # DELETE /stitches/1.json
  def destroy
    @stitch = Stitch.find(params[:id])
    @stitch.destroy

    respond_to do |format|
      format.html { redirect_to stitches_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/stitches_helper.rb
module StitchesHelper
end

app/views/stitches/_form.html.erb
<%= form_for(@stitch) do |f| %>
  <% if @stitch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stitch.errors.count, "error") %> prohibited this stitch from being saved:</h2>

      <ul>
      <% @stitch.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <% if @stitch.scroll %>
    <%= f.hidden_field :scroll_id %>
  <% else %>
    <div class="field">
      <%= f.label :scroll_id %><br />
      <%= f.number_field :scroll_id %>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :scribbling_id %><br />
    <%= f.select :scribbling_id, options_from_collection_for_select(Scribbling.all, :id, :body) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stitches/edit.html.erb
<h1>Editing stitch</h1>

<%= render 'form' %>

<%= link_to 'Show', @stitch %> |
<%= link_to 'Back', stitches_path %>

app/views/stitches/index.html.erb
<h1>Listing stitches</h1>

<table>
  <tr>
    <th>Scroll</th>
    <th>Scribbling</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @stitches.each do |stitch| %>
  <tr>
    <td><%= link_to stitch.scroll.title, stitch.scroll %></td>
    <td><%= link_to stitch.scribbling.body, stitch.scribbling %></td>
    <td><%= link_to 'Show', stitch %></td>
    <td><%= link_to 'Edit', edit_stitch_path(stitch) %></td>
    <td><%= link_to 'Destroy', stitch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Stitch', new_stitch_path %>

app/views/stitches/new.html.erb
<h1>New stitch</h1>

<%= render 'form' %>

<%= link_to 'Back', stitches_path %>

app/views/stitches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Scroll:</b>
  <%= @stitch.scroll_id %>
</p>

<p>
  <b>Scribbling:</b>
  <%= @stitch.scribbling_id %>
</p>


<%= link_to 'Edit', edit_stitch_path(@stitch) %> |
<%= link_to 'Back', stitches_path %>