config/routes.rb
Witchcraft::Application.routes.draw do
  resources :stitches

  resources :scrolls

  resources :scribblings

  resources :witches

end

app/models/scroll.rb
class Scroll < ActiveRecord::Base
  attr_accessible :title
  
  has_many :stitches
  has_many :scribblings, :through => :stitches
end

app/controllers/scrolls_controller.rb
class ScrollsController < ApplicationController
  # GET /scrolls
  # GET /scrolls.json
  def index
    @scrolls = Scroll.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @scrolls }
    end
  end

  # GET /scrolls/1
  # GET /scrolls/1.json
  def show
    @scroll = Scroll.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @scroll }
    end
  end

  # GET /scrolls/new
  # GET /scrolls/new.json
  def new
    @scroll = Scroll.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @scroll }
    end
  end

  # GET /scrolls/1/edit
  def edit
    @scroll = Scroll.find(params[:id])
  end

  # POST /scrolls
  # POST /scrolls.json
  def create
    @scroll = Scroll.new(params[:scroll])

    respond_to do |format|
      if @scroll.save
        format.html { redirect_to @scroll, notice: 'Your scroll is now ready for spell storification.  Beware of black magic.' }
        format.json { render json: @scroll, status: :created, location: @scroll }
      else
        format.html { render action: "new" }
        format.json { render json: @scroll.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /scrolls/1
  # PUT /scrolls/1.json
  def update
    @scroll = Scroll.find(params[:id])

    respond_to do |format|
      if @scroll.update_attributes(params[:scroll])
        format.html { redirect_to @scroll, notice: 'Scroll was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @scroll.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scrolls/1
  # DELETE /scrolls/1.json
  def destroy
    @scroll = Scroll.find(params[:id])
    @scroll.destroy

    respond_to do |format|
      format.html { redirect_to scrolls_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/scrolls_helper.rb
module ScrollsHelper
end

app/views/scrolls/_form.html.erb
<%= form_for(@scroll) do |f| %>
  <% if @scroll.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@scroll.errors.count, "error") %> prohibited this scroll from being saved:</h2>

      <ul>
      <% @scroll.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_area :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scrolls/edit.html.erb
<h1>Editing scroll</h1>

<%= render 'form' %>

<%= link_to 'Show', @scroll %> |
<%= link_to 'Back', scrolls_path %>

app/views/scrolls/index.html.erb
<h1>Listing scrolls</h1>

<table>
  <tr>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @scrolls.each do |scroll| %>
  <tr>
    <td><%= link_to scroll.title, scroll %></td>
    <td><%= link_to 'Edit', edit_scroll_path(scroll) %></td>
    <td><%= link_to 'Destroy', scroll, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Scroll', new_scroll_path %>

app/views/scrolls/new.html.erb
<h1>New scroll</h1>

<%= render 'form' %>

<%= link_to 'Back', scrolls_path %>

app/views/scrolls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @scroll.title %>
</p>

<ul>
  <% @scroll.scribblings.each do |scribbling| %>
    <li>
      <%= link_to(scribbling.id, scribbling_path(scribbling.id)) %>
      <%= scribbling.body %>
    </li>
  <% end %>
</ul>
<div>
  <%= link_to 'Stitch on this scroll.', new_stitch_path(:scroll_id => @scroll.id) %>
</div>

<%= link_to 'Edit', edit_scroll_path(@scroll) %> |
<%= link_to 'Back', scrolls_path %>