config/routes.rb
Witchcraft::Application.routes.draw do
  resources :stitches

  resources :scrolls

  resources :scribblings

  resources :witches

end

app/models/witch.rb
class Witch < ActiveRecord::Base
  attr_accessible :email, :first_name, :last_name, :witch_name
end

app/controllers/witches_controller.rb
class WitchesController < ApplicationController
  # GET /witches
  # GET /witches.json
  def index
    @witches = Witch.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @witches }
    end
  end

  # GET /witches/1
  # GET /witches/1.json
  def show
    @witch = Witch.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @witch }
    end
  end

  # GET /witches/new
  # GET /witches/new.json
  def new
    @witch = Witch.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @witch }
    end
  end

  # GET /witches/1/edit
  def edit
    @witch = Witch.find(params[:id])
  end

  # POST /witches
  # POST /witches.json
  def create
    @witch = Witch.new(params[:witch])

    respond_to do |format|
      if @witch.save
        format.html { redirect_to @witch, notice: 'Witch was successfully created.' }
        format.json { render json: @witch, status: :created, location: @witch }
      else
        format.html { render action: "new" }
        format.json { render json: @witch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /witches/1
  # PUT /witches/1.json
  def update
    @witch = Witch.find(params[:id])

    respond_to do |format|
      if @witch.update_attributes(params[:witch])
        format.html { redirect_to @witch, notice: 'Witch was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @witch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /witches/1
  # DELETE /witches/1.json
  def destroy
    @witch = Witch.find(params[:id])
    @witch.destroy

    respond_to do |format|
      format.html { redirect_to witches_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/witches_helper.rb
module WitchesHelper
end

app/views/witches/_form.html.erb
<%= form_for(@witch) do |f| %>
  <% if @witch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@witch.errors.count, "error") %> prohibited this witch from being saved:</h2>

      <ul>
      <% @witch.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :witch_name %><br />
    <%= f.text_field :witch_name %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/witches/edit.html.erb
<h1>Editing witch</h1>

<%= render 'form' %>

<%= link_to 'Show', @witch %> |
<%= link_to 'Back', witches_path %>

app/views/witches/index.html.erb
<h1>Listing witches</h1>

<table>
  <tr>
    <th>Witch name</th>
    <th>First name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @witches.each do |witch| %>
  <tr>
    <td><%= witch.witch_name %></td>
    <td><%= witch.first_name %></td>
    <td><%= link_to 'Show', witch %></td>
    <td><%= link_to 'Morph', edit_witch_path(witch) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Witch', new_witch_path %>

app/views/witches/new.html.erb
<h1>New witch</h1>

<%= render 'form' %>

<%= link_to 'Back', witches_path %>

app/views/witches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Witch name:</b>
  <%= @witch.witch_name %>
</p>

<p>
  <b>First name:</b>
  <%= @witch.first_name %>
</p>


<%= link_to 'Edit', edit_witch_path(@witch) %> |
<%= link_to 'Back', witches_path %>