config/routes.rb
Witchcraft::Application.routes.draw do
  resources :stitches

  resources :scrolls

  resources :scribblings

  resources :witches

end

app/models/scribbling.rb
class Scribbling < ActiveRecord::Base
  attr_accessible :body, :witch_id

  has_many :stitches
  has_many :scrolls, :through => :stitches
end

app/controllers/scribblings_controller.rb
class ScribblingsController < ApplicationController
  # GET /scribblings
  # GET /scribblings.json
  def index
    @scribblings = Scribbling.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @scribblings }
    end
  end

  # GET /scribblings/1
  # GET /scribblings/1.json
  def show
    @scribbling = Scribbling.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @scribbling }
    end
  end

  # GET /scribblings/new
  # GET /scribblings/new.json
  def new
    @scribbling = Scribbling.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @scribbling }
    end
  end

  # GET /scribblings/1/edit
  def edit
    @scribbling = Scribbling.find(params[:id])
  end

  # POST /scribblings
  # POST /scribblings.json
  def create
    @scribbling = Scribbling.new(params[:scribbling])

    respond_to do |format|
      if @scribbling.save
        format.html { redirect_to @scribbling, notice: 'Scribbling was successfully created.' }
        format.json { render json: @scribbling, status: :created, location: @scribbling }
      else
        format.html { render action: "new" }
        format.json { render json: @scribbling.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /scribblings/1
  # PUT /scribblings/1.json
  def update
    @scribbling = Scribbling.find(params[:id])

    respond_to do |format|
      if @scribbling.update_attributes(params[:scribbling])
        format.html { redirect_to @scribbling, notice: 'Scribbling was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @scribbling.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scribblings/1
  # DELETE /scribblings/1.json
  def destroy
    @scribbling = Scribbling.find(params[:id])
    @scribbling.destroy

    respond_to do |format|
      format.html { redirect_to scribblings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/scribblings_helper.rb
module ScribblingsHelper
end

app/views/scribblings/_form.html.erb
<%= form_for(@scribbling) do |f| %>
  <% if @scribbling.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@scribbling.errors.count, "error") %> prohibited this scribbling from being saved:</h2>

      <ul>
      <% @scribbling.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :witch_id %><br />
    <%= f.select :witch_id, options_from_collection_for_select(Witch.all, :id, :witch_name) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scribblings/edit.html.erb
<h1>Editing scribbling</h1>

<%= render 'form' %>

<%= link_to 'Show', @scribbling %> |
<%= link_to 'Back', scribblings_path %>

app/views/scribblings/index.html.erb
<h1>Listing scribblings</h1>

<table>
  <tr>
    <th>Body</th>
    <th>Witch</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @scribblings.each do |scribbling| %>
  <tr>
    <td><%= scribbling.body %></td>
    <td><%= Witch.find(scribbling.witch_id).witch_name if scribbling.witch_id? %></td>
    <td><%= link_to 'Show', scribbling %></td>
    <td><%= link_to 'Edit', edit_scribbling_path(scribbling) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Scribbling', new_scribbling_path %>

app/views/scribblings/new.html.erb
<h1>New scribbling</h1>

<%= render 'form' %>

<%= link_to 'Back', scribblings_path %>

app/views/scribblings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Body:</b>
  <%= @scribbling.body %>
</p>

<% if @scribbling.witch_id %>
  <p>
    <b>Witch:</b>
    <%= Witch.find(@scribbling.witch_id).witch_name %>
  </p>
<% end %>

<%= link_to 'Edit', edit_scribbling_path(@scribbling) %> |
<%= link_to 'Back', scribblings_path %>